### ISSUE TITLE
May I ask why you configure cell's data in func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) rather than func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell

### ISSUE THREAD

**Issue by JeromeTW** [gautam1001/Smart-Lazy-Loading#1]
May I ask why you configure cell's data in func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) rather than func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell??

What are the benefits of such an approach? Is there evidence?

Thanks for your sharing, I learn a lot from your project~~~

**Comment by jwd-ali** [comment]
yes .. you can ask this question
its because willDisplay called before cellForItem

**Comment by gautam1001** [comment]
@jwd-ali 
Thanks! for your contribution.

**Comment by gautam1001** [comment]
@JeromeTW 
I apologize for not reverting back as I was not active on Medium from last few months. 

The reason for writing the cell configuration code inside the "**will display**" cell method is that the "**will display**" cell method is being called after every time the cell is created and appears on the screen so the configuration of the cell will work only in this condition. And also it removes the overhead of calling the download image API for the cells which are not on the screen but created by the dequeue cell mechanism when you scrolls up.

I hope this will give you a clear idea of using the configuration of the cell inside will display.
 
You can get the stack trace of the collection view Datasource and Delegate methods by putting the simple print statement inside these methods.
